// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3DFC7c57nIT3dBCBPT--4anWn9bylPAM',
    appId: '1:574918835946:web:6bc18c158ba8c1d3c3a193',
    messagingSenderId: '574918835946',
    projectId: 'flutterproject-349',
    authDomain: 'flutterproject-349.firebaseapp.com',
    storageBucket: 'flutterproject-349.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbMArT5z-4sVC_aBJdOPe0BBrKp-OQerM',
    appId: '1:574918835946:android:2dfd1a634a9736d7c3a193',
    messagingSenderId: '574918835946',
    projectId: 'flutterproject-349',
    storageBucket: 'flutterproject-349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1wKYMw1oiGmRiqqCYhJHUPCJPjr0uZHs',
    appId: '1:574918835946:ios:adfc19c184764bf5c3a193',
    messagingSenderId: '574918835946',
    projectId: 'flutterproject-349',
    storageBucket: 'flutterproject-349.firebasestorage.app',
    androidClientId: '574918835946-39s4h2k89hanu2tais1gospn6g1dk104.apps.googleusercontent.com',
    iosClientId: '574918835946-820uh5rqp2a4vh282ukr8u4ess43rmea.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackivore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1wKYMw1oiGmRiqqCYhJHUPCJPjr0uZHs',
    appId: '1:574918835946:ios:adfc19c184764bf5c3a193',
    messagingSenderId: '574918835946',
    projectId: 'flutterproject-349',
    storageBucket: 'flutterproject-349.firebasestorage.app',
    androidClientId: '574918835946-39s4h2k89hanu2tais1gospn6g1dk104.apps.googleusercontent.com',
    iosClientId: '574918835946-820uh5rqp2a4vh282ukr8u4ess43rmea.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackivore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3DFC7c57nIT3dBCBPT--4anWn9bylPAM',
    appId: '1:574918835946:web:af34c20ccb3942e7c3a193',
    messagingSenderId: '574918835946',
    projectId: 'flutterproject-349',
    authDomain: 'flutterproject-349.firebaseapp.com',
    storageBucket: 'flutterproject-349.firebasestorage.app',
  );

}